[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32WB55RGVx --speed 950 --connect-under-reset"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"
